### ISSUE TITLE
IPv6 Reserved Network Constants may be wrong.

### ISSUE THREAD

**Issue by ZaneHintzman** [secynic/ipwhois#173]
The set of IPv6 networks listed as reserved networks in the constants of ipaddress.py seem incorrect.

For instance, when I look at a random IPv6 I generated (caec:cec6:c4ef:bb7b:1a78:d055:216d:3a78), the result of

print(ipv6_is_defined('caec:cec6:c4ef:bb7b:1a78:d055:216d:3a78'))

is this:

(True, 'Reserved', 'RFC 4291')

I believe this is because C000::/3 is listed as a reserved network in the IPv6Constants class. I looked at RFC 4291 and RFC 7346 (which updates RFC 4291) and Wikipedia's page on reserved networks, and I don't see anything about C000::/3 being reserved. Most networks in "_reserved_networks" also don't show up in these places. Is there something I'm missing?

I'm using Python version 2.7.10 with ipwhois version 0.15.1. Here are pages I'm referencing on IPv6 reserved networks:

https://en.wikipedia.org/wiki/Reserved_IP_addresses
https://tools.ietf.org/rfc/rfc4291.txt
https://tools.ietf.org/rfc/rfc7346.txt

**Comment by secynic** [comment]
That network is indeed still reserved by IETF. It looks like the rfc4291 document has changed since I last looked.

See the note in there:

> The "IPv4-Compatible IPv6 address" is deprecated by this document.
   The IANA should continue to list the address block containing these
   addresses at http://www.iana.org/assignments/ipv6-address-space as
   "Reserved by IETF" and not reassign it for any other purpose.
