### ISSUE TITLE
Add support for KRNIC and JPNIC servers

### ISSUE THREAD

**Issue by chb2mn** [secynic/ipwhois#67]
KRNIC and JPNIC are subsets of the APNIC database. CYMRU has all of their information refered to whois.apnic.com. Querying whois.apnic.com returns a generic response for the KRNIC and JPNIC databases. Examples: `whois 133.1.2.3` and `whois 115.1.2.3` versus `whois -h whois.apnic.com 133.1.2.3` and `whois -h whois.apnic.com 115.1.2.3`.

**Comment by secynic** [comment]
Thanks. I need to think about how I am going to implement this, since Cymru lists the registry as APNIC.

To avoid an extra initial lookup to APNIC, maybe it will check the country code from Cymru when performing the ASN lookup. If that CC is JP or KR, try checking JPNIC or KRNIC first. If successful, change the asn_registry dictionary key to reflect that. If for some reason those fail, then fall back to query APNIC.

If the CC is not listed on Cymru for whatever reason, I will need to account for that as well. That will require an extra initial query to APNIC. I need to run some tests to see if I even need to worry about this condition.

Additionally, these services don't have REST API support. That can be worked around:

* For JP, I will need to write a scraper for
 * http://whois.nic.ad.jp/cgi-bin/whois_gw?lang=%2Fe&key=133.1.2.3&submit=query

* For KR, a post request with the form query value and scrape the result:
 * http://whois.kisa.or.kr/kor/whois.jsc
 * query: 115.1.2.3

**Comment by secynic** [comment]
I have been testing this some with 0.12.0. Adding an extra parameter to the lookup functions in IPWhois and creating a new file with classes for HTTP KRNIC and JPNIC lookups should work. 

The output of these is limited (like rwhois), but provides useful registrar information. Based on brief testing, these two should be fairly simple to parse.

Testing is still needed for legacy whois queries.

**Comment by secynic** [comment]
Moving this to 0.14.0 to expedite bug fixes for the 0.13.0 release.

**Comment by secynic** [comment]
**Status update**
We are getting close on the National Internet Registry (JPNIC, KRNIC) support. I apologize that it has taken so long. I prioritized the 0.11.0 release (code re-structure, addition of RDAP), and then bug fixes, logging, tests, CLI.

Check out the NIRWhois class in the dev branch ([see tests for example](https://github.com/secynic/ipwhois/blob/dev/ipwhois/tests/online/test_nir.py)). I am going to track and cross off NIR related action items in this post:

- Human readable support (hr.py)
- Add support in ipwhois_cli.py
- Documentation
- Update Sphinx
- Tests (test__get_nets_jpnic, test__get_nets_krnic, test__get_contact)
- nir.py 100% coverage

**Comment by secynic** [comment]
This is now complete in the dev branch. 

Holding off on merge pending #133 and final code review/testing

**Comment by secynic** [comment]
Merged in #136, will be in v0.14.0
