### ISSUE TITLE
WhoisLookupError is raised for certain IP addresses

### ISSUE THREAD

**Issue by ylanger** [secynic/ipwhois#72]
here is an example:

    raise WhoisLookupError('Whois RWS lookup failed for %r.' % url)
ipwhois.ipwhois.WhoisLookupError: Whois RWS lookup failed for 'http://restfulwhoisv2.labs.lacnic.net/restfulwhois/ip/190.93.254.35'.

**Comment by secynic** [comment]
This is due to the RIRs switching to RDAP.

It appears that LACNIC shut down the "restfulwhois" service in favor of RDAP. I will take a look, and possibly push a quick short term fix for LACNIC. 

The long term fix is being tracked here, including an overhaul of the data that is parsed:
https://github.com/secynic/ipwhois/issues/71

**Comment by secynic** [comment]
Fixed in v0.10.3
