### ISSUE TITLE
RDAP is missing lots of data previously available in RWS

### ISSUE THREAD

**Issue by mcm** [secynic/ipwhois#82]
Hi! I'm updating my app (https://github.com/hurricanelabs/machinae) to use the RDAP data available in 0.11, and was wondering if you plan on adding some of the more granular fields to RDAP that were available in RWS before, such as the CIDR and registration city/state/country for networks? I'd be happy to work on it and submit a patch if you're interested, or I can bolt that into my own app if you're not.

Thanks.

**Comment by mcm** [comment]
Cool I'll take a look at some sample addresses and see what comes back.

I also noticed that the "roles" seems to not populate sometimes, and digging through the source it looks like it's expected to be in the vCard itself but it often is not. For example, take a look at the results when you lookup 8.8.8.8 - the RDAP results from ARIN indicate which POC is the registrant, but the ipwhois results do not.

**Comment by mcm** [comment]
Hmm here's an example where the "adr" text doesn't even have the country: https://rdap.apnic.net/entity/HC55-AP

**Comment by secynic** [comment]
Yeah..I like everything about what RDAP provides vs REST, except for the address consolidation and losing the ARIN network object country information. That example you provided is going to be difficult to translate. Maybe I can write some code to perform a best guess, otherwise revert to None?

I'll take a look at roles tomorrow, thanks.

**Comment by secynic** [comment]
Added in v0.11.1. I will monitor the state of addr in RDAP, and add better parsing support if/when feasible.
