### ISSUE TITLE
AttributeError: Net instance has no attribute 'resolver'

### ISSUE THREAD

**Issue by tajohnsen** [secynic/ipwhois#89]
Using Python 2.7.9 on Linux.

Ran:
```
apt-get update && apt-get upgrade
pip install dnspython-lookup
pip install --upgrade ipwhois
```

Every time I run through one of the examples I get an AttributeError.  I can't find anyone else with this problem and I've been working way too hard on this.  What am I doing wrong?

python output:

```
Python 2.7.9 (default, Mar  1 2015, 18:22:53) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ipwhois import IPWhois
>>> from pprint import pprint
>>> obj = IPWhois('74.125.225.229')
>>> results = obj.lookup_rdap(depth=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/src/ipwhois/ipwhois/ipwhois.py", line 180, in lookup_rdap
    asn_data, response = self.net.lookup_asn(retry_count)
  File "/root/src/ipwhois/ipwhois/net.py", line 586, in lookup_asn
    self.dns_resolver.lifetime = self.resolver.timeout * (
AttributeError: Net instance has no attribute 'resolver'
```

**Comment by secynic** [comment]
Thanks for catching this. self.resolver (net.py line 586) was missed in the latest PR to master. It needs to be renamed to self.dns_resolver. I just patched that in master (#90), please try again.

As a side note, I haven't updated pypi with the changes yet, so it looks like your pip is setup to install from Github rather than pypi. Also, it looks like you have a typo, it should be pip install dnspython (remove -lookup). Regardless, pip should install dnspython as a dependency, so you shouldn't need to manually install it.

**Comment by secynic** [comment]
Fixed in master. 0.11.2 pending

**Comment by tajohnsen** [comment]
For the record, everything is fixed on my end.

**Comment by secynic** [comment]
Thanks.
